[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#d33682"
backgroundColor = "#1e1e1e"
secondaryBackgroundColor = "#282c34"
textColor = "#ffffff"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[browser]
gatherUsageStats = false